-- =========================================================
-- Migration: Professional ticketing upgrade
-- Roles, categories, SLA, reporter scope, performance indexes
-- =========================================================

alter type public.app_role add value if not exists 'reporter';
alter type public.app_role add value if not exists 'project_manager';
alter type public.app_role add value if not exists 'projects_director';

create table if not exists public.ticket_categories (
  id bigint generated always as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.ticket_categories (name)
values
  ('الحريق'),
  ('الكهرباء'),
  ('التكييف'),
  ('المدنى'),
  ('المطابخ')
on conflict (name) do nothing;

alter table public.tickets
  add column if not exists ticket_number bigint generated by default as identity,
  add column if not exists title text,
  add column if not exists category_id bigint references public.ticket_categories(id) on delete set null,
  add column if not exists gps_enabled boolean not null default false,
  add column if not exists first_response timestamptz null,
  add column if not exists closed_at timestamptz null,
  add column if not exists assigned_to uuid generated always as (coalesce(assigned_technician_id, assigned_engineer_id)) stored;

create unique index if not exists idx_tickets_ticket_number_unique on public.tickets(ticket_number);
create index if not exists idx_tickets_zone_id_perf on public.tickets(zone_id);
create index if not exists idx_tickets_status_perf on public.tickets(status);
create index if not exists idx_tickets_assigned_to_perf on public.tickets(assigned_to);
create index if not exists idx_tickets_created_by_created_at on public.tickets(created_by, created_at desc);
create index if not exists idx_tickets_category_id on public.tickets(category_id);

create table if not exists public.ticket_attachments (
  id bigint generated always as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete cascade,
  file_url text not null,
  file_type text not null default 'image',
  created_at timestamptz not null default now()
);

create index if not exists idx_ticket_attachments_ticket_id on public.ticket_attachments(ticket_id);
create index if not exists idx_ticket_attachments_created_at on public.ticket_attachments(created_at);

create or replace function public.can_access_ticket(p_ticket_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select auth.uid() as uid, public.current_user_role() as role
  ),
  t as (
    select *
    from public.tickets
    where id = p_ticket_id
  )
  select
    case
      when (select role from me)::text in ('admin', 'project_manager', 'projects_director') then true
      when (select role from me)::text = 'engineer' then
        exists (
          select 1
          from t
          join public.engineer_zones ez on ez.zone_id = t.zone_id
          where ez.engineer_id = (select uid from me)
        )
      when (select role from me)::text = 'supervisor' then
        exists (
          select 1
          from t
          left join public.profiles tech on tech.id = t.assigned_technician_id
          where
            t.assigned_supervisor_id = (select uid from me)
            or tech.supervisor_id = (select uid from me)
        )
      when (select role from me)::text = 'technician' then
        exists (
          select 1
          from t
          where t.assigned_technician_id = (select uid from me)
        )
      when (select role from me)::text = 'reporter' then
        exists (
          select 1
          from t
          where t.created_by = (select uid from me)
        )
      else false
    end
$$;

drop policy if exists "tickets_insert_policy" on public.tickets;
create policy "tickets_insert_policy"
on public.tickets
for insert
to authenticated
with check (
  public.current_user_role()::text in ('admin', 'project_manager', 'projects_director')
  or (
    public.current_user_role()::text = 'supervisor'
    and assigned_supervisor_id = auth.uid()
  )
  or (
    public.current_user_role()::text = 'reporter'
    and created_by = auth.uid()
    and assigned_supervisor_id is null
    and assigned_technician_id is null
    and assigned_engineer_id is null
  )
);

drop policy if exists "tickets_update_policy" on public.tickets;
create policy "tickets_update_policy"
on public.tickets
for update
to authenticated
using (public.can_access_ticket(id))
with check (
  public.current_user_role()::text in ('admin', 'project_manager', 'projects_director')
  or (
    public.current_user_role()::text = 'supervisor'
    and (
      assigned_supervisor_id = auth.uid()
      or exists (
        select 1 from public.profiles tech
        where tech.id = assigned_technician_id
          and tech.supervisor_id = auth.uid()
      )
    )
  )
  or (
    public.current_user_role()::text = 'technician'
    and assigned_technician_id = auth.uid()
  )
  or (
    public.current_user_role()::text = 'reporter'
    and created_by = auth.uid()
    and status = 'fixed'::public.ticket_status
  )
);

drop policy if exists "tickets_delete_policy" on public.tickets;
create policy "tickets_delete_policy"
on public.tickets
for delete
to authenticated
using (public.current_user_role()::text in ('admin', 'project_manager', 'projects_director'));

alter table public.ticket_categories enable row level security;
alter table public.ticket_categories force row level security;
drop policy if exists "ticket_categories_select_policy" on public.ticket_categories;
create policy "ticket_categories_select_policy"
on public.ticket_categories
for select
to authenticated
using (is_active = true or public.current_user_role()::text in ('admin', 'project_manager', 'projects_director'));
drop policy if exists "ticket_categories_write_policy" on public.ticket_categories;
create policy "ticket_categories_write_policy"
on public.ticket_categories
for all
to authenticated
using (public.current_user_role()::text in ('admin', 'project_manager', 'projects_director'))
with check (public.current_user_role()::text in ('admin', 'project_manager', 'projects_director'));

alter table public.ticket_attachments enable row level security;
alter table public.ticket_attachments force row level security;
drop policy if exists "ticket_attachments_select_policy" on public.ticket_attachments;
create policy "ticket_attachments_select_policy"
on public.ticket_attachments
for select
to authenticated
using (public.can_access_ticket(ticket_id));
drop policy if exists "ticket_attachments_insert_policy" on public.ticket_attachments;
create policy "ticket_attachments_insert_policy"
on public.ticket_attachments
for insert
to authenticated
with check (
  public.can_access_ticket(ticket_id)
  and uploaded_by = auth.uid()
);
drop policy if exists "ticket_attachments_update_policy" on public.ticket_attachments;
create policy "ticket_attachments_update_policy"
on public.ticket_attachments
for update
to authenticated
using (false)
with check (false);
drop policy if exists "ticket_attachments_delete_policy" on public.ticket_attachments;
create policy "ticket_attachments_delete_policy"
on public.ticket_attachments
for delete
to authenticated
using (public.current_user_role()::text in ('admin', 'project_manager', 'projects_director'));

drop policy if exists "ticket_messages_update_policy" on public.ticket_messages;
create policy "ticket_messages_update_policy"
on public.ticket_messages
for update
to authenticated
using (false)
with check (false);

drop policy if exists "ticket_messages_delete_policy" on public.ticket_messages;
create policy "ticket_messages_delete_policy"
on public.ticket_messages
for delete
to authenticated
using (false);

create or replace function public.set_ticket_first_response()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.profiles p
    where p.id = new.sender_id
      and p.role::text = 'technician'
  ) then
    update public.tickets t
    set first_response = coalesce(t.first_response, new.created_at)
    where t.id = new.ticket_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_ticket_messages_first_response on public.ticket_messages;
create trigger trg_ticket_messages_first_response
after insert on public.ticket_messages
for each row execute function public.set_ticket_first_response();

create or replace function public.set_ticket_closed_at()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'fixed'::public.ticket_status and old.status is distinct from 'fixed'::public.ticket_status then
    new.closed_at = coalesce(new.closed_at, now());
  elsif old.status = 'fixed'::public.ticket_status and new.status is distinct from 'fixed'::public.ticket_status then
    new.closed_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_tickets_set_closed_at on public.tickets;
create trigger trg_tickets_set_closed_at
before update on public.tickets
for each row execute function public.set_ticket_closed_at();
